$(document).ready(function(){
	//header划过事件
	$(".hea1-hover").hover(function(){
        $(".h-a2-hover").toggle();
	});
	$(".hea2-hover").hover(function(){
        $(".h-a3-hover").toggle();
	});
	$(".hea3-hover").hover(function(){
        $(".h-a4-hover").toggle();
	});
	$(".hea-rig-h2").hover(function(){
        $(".hea-r-2-h").toggle();
	});
	$(".hea-rig-h3").hover(function(){
        $(".hea-r-3-h").toggle();
	});
	//搜索点击事件
	$(".hea-r-1").click(function(){
        $(".hea-l-font").hide();
        $(".hea-rig").hide();
        $(".sousuo-click").show(500);
	});
	$(".click-r4").click(function(){
        $(".hea-l-font").show();
        $(".hea-rig").show();
        $(".sousuo-click").hide();
	});
	//nav 划过事件
	$(".nav-li2").hover(function(){
        $(".nav-li2-h").toggle();
	});
	$(".nav-li3").hover(function(){
        $(".nav-li3-h").toggle();
	});
	$(".nav-li4").hover(function(){
        $(".nav-li4-h").toggle();
	});
	$(".nav-li5").hover(function(){
        $(".nav-li5-h").toggle();
	});
	//nav点击事件
	$(".img01").click(function(){
        $(".section1").show();
        $(".section2").hide();
	});
	$(".img02").click(function(){
        $(".section1").hide();
        $(".section2").show();
	});
	//section滑过事件
	$(".one-1").hover(function(){
        $(".one-1-h").slideToggle(300);
	});
    $(".one-2").hover(function(){
        $(".one-2-h").slideToggle(300);
	});
	$(".one-3").hover(function(){
        $(".one-3-h").slideToggle(300);
	});
	$(".two-1").hover(function(){
        $(".two-1-h").slideToggle(300);
	});
    $(".two-2").hover(function(){
        $(".two-2-h").slideToggle(300);
	});
	$(".two-3").hover(function(){
        $(".two-3-h").slideToggle(300);
	});
	$(".thr-1").hover(function(){
        $(".thr-1-h").slideToggle(300);
	});
    $(".thr-2").hover(function(){
        $(".thr-2-h").slideToggle(300);
	});
	$(".thr-3").hover(function(){
        $(".thr-3-h").slideToggle(300);
	});
	$(".fou-1").hover(function(){
        $(".fou-1-h").slideToggle(300);
	});
    $(".fou-2").hover(function(){
        $(".fou-2-h").slideToggle(300);
	});
	$(".fou-3").hover(function(){
        $(".fou-3-h").slideToggle(300);
	});
	$(".fiv-1").hover(function(){
        $(".fiv-1-h").slideToggle(300);
	});
    $(".fiv-2").hover(function(){
        $(".fiv-2-h").slideToggle(300);
	});
	$(".fiv-3").hover(function(){
        $(".fiv-3-h").slideToggle(300);
	});
	$(".six-1").hover(function(){
        $(".six-1-h").slideToggle(300);
	});
    $(".six-2").hover(function(){
        $(".six-2-h").slideToggle(300);
	});
	$(".six-3").hover(function(){
        $(".six-3-h").slideToggle(300);
	});
	$(".sev-1").hover(function(){
        $(".sev-1-h").slideToggle(300);
	});
    $(".sev-2").hover(function(){
        $(".sev-2-h").slideToggle(300);
	});
	$(".sev-3").hover(function(){
        $(".sev-3-h").slideToggle(300);
	});
    $(".eig-1").hover(function(){
        $(".eig-1-h").slideToggle(300);
	});
    $(".eig-2").hover(function(){
        $(".eig-2-h").slideToggle(300);
	});
	$(".eig-3").hover(function(){
        $(".eig-3-h").slideToggle(300);
	});
    //aside
    $(".li01").hover(function(){
        $(".li01-h").toggle();
    });
    $(".li02").hover(function(){
        $(".li02-h").toggle();
    });
    $(".li03").hover(function(){
        $(".li03-h").toggle();
    });
    $(".li04").hover(function(){
        $(".li04-h").toggle();
    });
    $(".li05").hover(function(){
        $(".li05-h").toggle();
    });
    $(".li06").hover(function(){
        $(".li06-h").toggle();
    });
    $(".li07").hover(function(){
        $(".li07-h").toggle();
    });
    $(".li08").hover(function(){
        $(".li08-h").toggle();
    }); 
    $(".li09").hover(function(){
        $(".li09-h").toggle();
    });
    $(".li010").hover(function(){
        $(".li010-h").toggle();
    });
    $(".li001").hover(function(){
        $(".span-show1").toggle();
    });
    $(".li002").hover(function(){
        $(".span-show2").toggle();
    });
    $(".li003").hover(function(){
        $(".span-show3").toggle();
    });
    $(".li004").hover(function(){
        $(".span-show4").toggle();
    });

	//footer划过事件
	$(".iph").hover(function(){
        $(".iph-h").toggle();
	});
	$(".ard").hover(function(){
        $(".ard-h").toggle();
	});

})